# Generated by Django 4.1.4 on 2022-12-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_url', models.URLField(max_length=2100)),
                ('video_url', models.URLField(max_length=2100)),
                ('img_url', models.URLField(max_length=2100)),
                ('date', models.DateTimeField()),
                ('download_count', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
