# Generated by Django 4.1.4 on 2022-12-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_tweets_tweet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='tweet_url',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='video_url',
        ),
    ]
