# Generated by Django 4.1.4 on 2022-12-27 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_tweet_tweet_url_tweet_username_tweet_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tweet',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='img_url',
            field=models.URLField(default='', max_length=2100),
        ),
    ]
