# Generated by Django 4.1.4 on 2022-12-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0007_alter_tweet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='download_count',
            field=models.IntegerField(default=1),
        ),
    ]
